# Generated by Django 5.0.7 on 2025-01-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_main',
            field=models.CharField(default='', max_length=100),
        ),
    ]
