# Generated by Django 5.0.7 on 2025-01-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0009_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
